# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Personal blog
description: >-
  Don't take everything you read here too seriously.
  Enjoy your stay!
baseurl: ""
url: "https://sosolidkk.github.io/"

header_pages:
  - about.md
  - portfolio.md

author:
  email: pedrochaveslimas3@gmail.com
  name: Jo√£o Pedro

# Build settings
theme: minima
minima:
  skin: dark
  social_links:
    twitter: #
    github: sosolidkk
    instagram: jpechaves
    telegram: sosolidkk

plugins:
  - jekyll-feed
